#!/usr/bin/make -f
# Makefile for DISTRHO Plugins #
# ---------------------------- #
# Created by falkTX
#
# Modified by Anguselheim Studios
#

# --------------------------------------------------------------
# Project name, used for binaries

NAME = real_knobs

# --------------------------------------------------------------
# Files to build

FILES_DSP = \
	real_knobs.cpp

# --------------------------------------------------------------
# Do some magic

include ../../Makefile.plugins.mk

# --------------------------------------------------------------
# Enable all possible plugin types

TARGETS += lv2_dsp

all: $(TARGETS)

# --------------------------------------------------------------
